name: BuildResults

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check out commons
      uses: actions/checkout@v2
      with:
        repository: equipognoss/Gnoss.Commons.OpenCORE
        path: ./Gnoss.Commons
        ref: main
    - name: change folder
      run: |
        cd ..
        mv Gnoss.Web.Results.OpenCORE/Gnoss.Commons Gnoss.Commons
        cd Gnoss.Web.Results.OpenCORE
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
